config/routes.rb
Rails.application.routes.draw do
  get 'user/index'
  get 'recently_heards/create'
  devise_for :users
  
  authenticated :user do
    resources :favorites, only: :index
    root to: "dashboard#index", as: :authenticated_root
    resources :search, only: [:index, :new], as: :searches
    resources :categories, only: :show
    resources :artists, only: :show
    resources :albums, only: :show do
      resources :recently_heards, only: :create
    end
    resources :songs, only: [] do
      post "/favorite", to: "favorites#create", on: :member, defaults: { format: :js, favoritable_type: 'Song' }
      delete "/favorite", to: "favorites#destroy", on: :member, defaults: { format: :js, favoritable_type: 'Song' }
    end
    resources :albums, only: [] do
      post "/favorite", to: "favorites#create", on: :member, defaults: { format: :js, favoritable_type: 'Album' }
      delete "/favorite", to: "favorites#destroy", on: :member, defaults: { format: :js, favoritable_type: 'Album' }
    end
    resources :artists, only: [] do
      post "/favorite", to: "favorites#create", on: :member, defaults: { format: :js, favoritable_type: 'Artist' }
      delete "/favorite", to: "favorites#destroy", on: :member, defaults: { format: :js, favoritable_type: 'Artist' }
    end
  end

  unauthenticated :user do
    root to: "home#index"
  end
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :category
  belongs_to :artist
  has_many :songs

  validates :title, presence: true
  validates :date, presence: true

  has_one_attached :cover
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :albums
  
    validates :name, presence: true
    has_one_attached :photo
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :albums
  
    validates :name, presence: true
    has_one_attached :image
  
    def artists
      Artist.joins(:albums).where(albums: { id: self.albums.ids }).distinct
    end
  
  
    def songs
      Song.joins(:album).where(albums: { id: self.albums.ids }).distinct
    end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :favoritable, polymorphic: true
end

app/models/recently_heard.rb
class RecentlyHeard < ApplicationRecord
  belongs_to :user
  belongs_to :album
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
  validates :title, presence: true
  has_one_attached :file
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites
  has_many :recently_heards
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def show
    @album = Album.find(params[:id])
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def show
    @artist = Artist.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @songs = Song.where("title LIKE ?", "%#{params[:search]}%")
    @albums = Album.where("title LIKE ?", "%#{params[:search]}%")
    @artists = Artist.where("name LIKE ?", "%#{params[:search]}%")
  end


  def new
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
    def favorite_button(favoritable)
      if current_user.favorites.where(favoritable: favoritable).exists?
        render_button(favoritable.id, favoritable.class, :delete, :fas)
      else
        render_button(favoritable.id, favoritable.class, :post, :far)
      end
    end
  
  
    private
  
  
        def render_button(id, type, method, icon_format)
        url = send("favorite_#{type.to_s.downcase}_path", id)
        link_to url, class: "has-text-white", data: { remote: true, method: method, kind: type.to_s, id: id } do
            content_tag :i, "", class: "#{icon_format} fa-heart fa-2x"
        end
        end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<section class="hero is-dark is-fullheight">
  <div class="hero-body has-text-centered">
    <div class="container">
      <h1 class="title has-text-weight-light">
        SEU APP DE <br />
        <span class="has-text-primary">MÚSICA</span>
      </h1>
      <br />
      <h2 class="subtitle has-text-weight-light white">
        Álbuns • Lançamentos<br />
        Mais tocadas • Recomendadas
      </h2>
      <br /><br />
      <%= link_to "CADASTRAR", new_user_registration_path, class: "button is-medium is-outlined is-primary" %>
    </div>
  </div>
</section>

app/views/search/index.html.erb
<section class="section has-text-white has-text-centered">
  <h2 class="is-size-5 has-text-weight-light">Resultados</h2>
  <br />
  <div class="field">
    <%= form_with url: searches_path, method: :get, local: true do |f| %>
      <p class="control has-icons-right">
        <%= f.text_field :search, class: "input is-medium", type: "text", placeholder: "Álbuns, Artistas ou Músicas" %>
        <span class="icon is-small is-right">
          <i class="fas fa-search"></i>
        </span>
      </p>
    <% end %>
  </div>

  <%= render "shared/tabs", artists: @artists, songs: @songs, albums: @albums %>
</section>

app/views/search/new.html.erb
<section class="section has-text-white has-text-centered">
  <h2 class="is-size-5 has-text-weight-light">Buscar</h2>
  <br />
  <div class="field">
    <%= form_with url: searches_path, method: :get, local: true do |f| %>
      <p class="control has-icons-right">
        <%= f.text_field :search, class: "input is-medium", type: "text", placeholder: "Álbuns, Artistas ou Músicas" %>
        <span class="icon is-small is-right">
          <i class="fas fa-search"></i>
        </span>
      </p>
    <% end %>
  </div>

  <div class="columns is-multiline is-mobile">
    <% Category.all.each do |category| %>
      <div class="column is-half-mobile is-one-quarter-desktop">
        <%= link_to category do %>  
          <%= image_tag url_for(category.image) %>
        <% end %>
      </div>
    <% end %>
  </div>
</section>