config/routes.rb
Rails.application.routes.draw do
  get 'user/index'
  get 'recently_heards/create'
  devise_for :users
  
  authenticated :user do
    resources :favorites, only: :index
    root to: "dashboard#index", as: :authenticated_root
    resources :search, only: [:index, :new], as: :searches
    resources :categories, only: :show
    resources :artists, only: :show
    resources :albums, only: :show do
      resources :recently_heards, only: :create
    end
    resources :songs, only: [] do
      post "/favorite", to: "favorites#create", on: :member, defaults: { format: :js, favoritable_type: 'Song' }
      delete "/favorite", to: "favorites#destroy", on: :member, defaults: { format: :js, favoritable_type: 'Song' }
    end
    resources :albums, only: [] do
      post "/favorite", to: "favorites#create", on: :member, defaults: { format: :js, favoritable_type: 'Album' }
      delete "/favorite", to: "favorites#destroy", on: :member, defaults: { format: :js, favoritable_type: 'Album' }
    end
    resources :artists, only: [] do
      post "/favorite", to: "favorites#create", on: :member, defaults: { format: :js, favoritable_type: 'Artist' }
      delete "/favorite", to: "favorites#destroy", on: :member, defaults: { format: :js, favoritable_type: 'Artist' }
    end
  end

  unauthenticated :user do
    root to: "home#index"
  end
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :category
  belongs_to :artist
  has_many :songs

  validates :title, presence: true
  validates :date, presence: true

  has_one_attached :cover
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :albums
  
    validates :name, presence: true
    has_one_attached :photo
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :albums
  
    validates :name, presence: true
    has_one_attached :image
  
    def artists
      Artist.joins(:albums).where(albums: { id: self.albums.ids }).distinct
    end
  
  
    def songs
      Song.joins(:album).where(albums: { id: self.albums.ids }).distinct
    end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :favoritable, polymorphic: true
end

app/models/recently_heard.rb
class RecentlyHeard < ApplicationRecord
  belongs_to :user
  belongs_to :album
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
  validates :title, presence: true
  has_one_attached :file
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites
  has_many :recently_heards
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def show
    @album = Album.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
    def favorite_button(favoritable)
      if current_user.favorites.where(favoritable: favoritable).exists?
        render_button(favoritable.id, favoritable.class, :delete, :fas)
      else
        render_button(favoritable.id, favoritable.class, :post, :far)
      end
    end
  
  
    private
  
  
        def render_button(id, type, method, icon_format)
        url = send("favorite_#{type.to_s.downcase}_path", id)
        link_to url, class: "has-text-white", data: { remote: true, method: method, kind: type.to_s, id: id } do
            content_tag :i, "", class: "#{icon_format} fa-heart fa-2x"
        end
        end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/shared/_menu.html.erb
<nav class="columns is-mobile is-dark navbar is-fixed-top">
  <div class="column is-2-desktop logo">
      <%= image_tag "logo.png" %>
  </div>

  <div class="column menu-button">
    <% if user_signed_in? %>
      <div class="dropdown is-hoverable is-pulled-right is-right">
        <div class="dropdown-trigger">
          <a class="icon is-large" aria-haspopup="true" aria-controls="dropdown-menu">
            <i class="fas fa-cog fa-2x has-text-white-bis"></i>
          </a>
        </div>
        <div class="dropdown-menu" id="dropdown-menu" role="menu">
          <div class="dropdown-content">
            <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
            <hr class="dropdown-divider">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </div>
      </div>
    <% else %>
      <%= link_to "ENTRAR", new_user_session_path, class: "button is-pulled-right is-outlined is-white" %>          
    <% end %>
  </div>
</nav>

app/views/shared/_tabs.html.erb
<div class="tabs is-small is-centered shared">
  <ul>
    <% if albums %>
      <li class="is-active">
        <a target="#albums">
          <span class="icon is-small"><i class="fas fa-compact-disc" aria-hidden="true"></i></span>
          <span>Álbums</span>
        </a>
      </li>
    <% end %>

    <% if artists %>
      <li>
        <a target="#artists">
          <span class="icon is-small"><i class="fas fa-user-circle" aria-hidden="true"></i></span>
          <span>Artistas</span>
        </a>
      </li>
    <% end %>

    <% if songs %>
      <li>
        <a target="#songs">
          <span class="icon is-small"><i class="fas fa-music" aria-hidden="true"></i></span>
          <span>Músicas</span>
        </a>
      </li>
    <% end %>
  </ul>
</div>

<div class="tabs-content">
  <% if albums %>
    <div id="albums" class="tab-item active">
      <div class="columns is-mobile is-multiline">
        <%= render albums %>
      </div>
    </div>
  <% end %>

  <% if artists %>
    <div id="artists" class="tab-item">
      <div class="columns is-mobile is-multiline">
        <%= render artists %>
      </div>
    </div>
  <% end %>

  <% if songs %>
    <div id="songs" class="tab-item">
      <div class="columns is-multiline">
        <div class="column is-12">
          <button id="play-all" class="button is-primary is-medium">
            <span class="icon"><i class="fas fa-play-circle"></i></span> 
            <span>Tocar Todas</span>
          </button>
        </div>
        <%= render songs %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_toolbar.html.erb
<% if user_signed_in? %>  
  <nav class="columns is-mobile is-dark navbar is-fixed-bottom toolbar">
    <div class="column has-text-centered">
      <%= link_to authenticated_root_path, class: "has-text-white" do %>
        <i class="fa fa-home fa-lg"></i>
      <% end %>
    </div>

    <div class="column has-text-centered">
      <%= link_to new_search_path, class: "has-text-white" do %>
        <i class="fa fa-search fa-lg"></i>
      <% end %>
    </div>

    <div class="column has-text-centered">
      <%= link_to favorites_path, class: "has-text-white" do %>
        <i class="fas fa-heart fa-lg"></i>
      <% end %>
    </div>
  </nav>
<% end %>